### ISSUE TITLE
后端打包失败

### ISSUE THREAD

**Issue by KunBuFenZi** [houlangs/Newlangs4#30]
NewlangsSpringbootApplicationTests.scan文件中 http://new.langs.ink的证书过期导致报错
[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   NewlangsSpringbootApplicationTests.scan:25 ? SSLHandshake PKIX path validation...
[INFO]
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  16.985 s
[INFO] Finished at: 2024-05-20T11:37:23+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project newlangs-springboot: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Users\kunbu\Downloads\Compressed\Newlangs4-main\newlangs-springboot\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by liuyuhang9066** [comment]
其实这个问题即使调时钟也没用，刚才试过，改成2024/04/22，然后抛404，同样是打不成包

**Comment by SunWuyuan** [comment]
找到并删掉遥测？












孙悟元
***@***.***

https://wuyuan.dev

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月22日(周三) 下午3:38
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [houlangs/Newlangs4] 后端打包失败 (Issue #30)




 
其实这个问题即使调时钟也没用，刚才试过，改成2024/04/22，然后抛404，同样是打不成包

**Comment by houlangs** [comment]
目前我们正着手解决这个问题，很快即可修复
