### ISSUE TITLE
无法登陆

### ISSUE THREAD

**Issue by lanpinggai666** [houlangs/Newlangs4#36]
一切都配置好了，前后端也编译了好几遍了，数据库也导入了。就是登陆不了，点登陆按钮没有任何反应，也没有报错。

**Comment by SunWuyuan** [comment]
浏览器控制台log发下，

**Comment by lanpinggai666** [comment]
你要不等几天？服务器被DDos了，不知道几天能好。。。
________________________________
发件人: 孙悟元 ***@***.***>
发送时间: 2024年7月2日 8:47
收件人: houlangs/Newlangs4 ***@***.***>
抄送: lanpinggai666 ***@***.***>; Author ***@***.***>
主题: Re: [houlangs/Newlangs4] 无法登陆 (Issue #36)


浏览器控制台log发下，

―

**Comment by houlangs** [comment]
是否更改了后端地址？可参照安装文档检查一下
