### ISSUE TITLE
希望大佬能出个php版或一键引导脚本

### ISSUE THREAD

**Issue by myitcloud** [houlangs/Newlangs4#71]
菜鸟表示希望大佬能出个php版或一键引导脚本

**Comment by SunWuyuan** [comment]
底层不一样，不可能

**Comment by SunWuyuan** [comment]
倒是一直在想要不要docker-compose部署版本，但是想了想项目本身就没多少配置和对环境的依赖，似乎没必要

而且docker-compose的安装对小白来说本身就是个大问题，不如宝塔自动安上四件套然后Java运行

**Comment by houlangs** [comment]
> 倒是一直在想要不要docker-compose部署版本，但是想了想项目本身就没多少配置和对环境的依赖，似乎没必要
> 
> 而且docker-compose的安装对小白来说本身就是个大问题，不如宝塔自动安上四件套然后Java运行

正确的，最大的困难应该在编译。
